name: Pylint and Tests

on: [push]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    container:
      image: manimcommunity/manim:v0.18.1
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
          pip install .

      - name: Analyze code with pylint
        run: |
          python -m pylint **/*.py

      - name: Run tests with pytest
        run: |
          python -m pytest -v
